### ISSUE TITLE
1.7 version changed to 1.7.0

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/pantry.core#45]
Here's the relevant parts of package.yml:

```
distributable:
  url: http://www.catb.org/~esr/wumpus/wumpus-{{version}}.tar.gz
  strip-components: 1

versions:
  - 1.7
```

Here's what happens when I try to build.

```
downloading
error: Uncaught Error: 404: http://www.catb.org/~esr/wumpus/wumpus-1.7.0.tar.gz
```

The url isn't http://www.catb.org/~esr/wumpus/wumpus-1.7.0.tar.gz, it's http://www.catb.org/~esr/wumpus/wumpus-1.7.tar.gz.

Yes, this is a really important package. Don't ask me why.
