### ISSUE TITLE
{{version.raw}} clips zeros

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/pantry.core#60]
I'm not sure this goes in this repo but I think it does so here it is.

```
distributable:
  url: https://downloads.sourceforge.net/project/lame/lame/{{version.raw}}/lame-{{version.raw}}.tar.gz
  strip-components: 1

versions:
  - 3.100
```

Produced an error:

```
error: Uncaught (in promise) Error: 404: https://downloads.sourceforge.net/project/lame/lame/3.1/lame-3.1.tar.gz
```

The url should be https://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
